# -*- coding: utf-8 -*-
"""workshop-BBSB-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JH0y-xdgHH9pnmQFi9ugZHknSXuR8Ez-

# Python programming

### variable declaration
"""

a=10
print(a, type(a))

b=10.5
print(b, type(b))

b=50
print(b, type(b))



"""### operators

```

*   arithemetic operator
*   relational operator
*  logical operator
*  bitwise opeartor



"""

a=10 * 2
print(a)



"""### looping"""

# print table of 5
# 5 * 1 =5
# 5 * 2 = 10
# 5 * 3 = 15  .....

# initalization
# while ( contidition)
#   inc/dec

cnt = 1
while cnt <= 10 :
  print(5 * cnt)
  cnt = cnt + 1

# for (i=10; i<100 ; i++){  } printf("%d",i);
for i in range(1,15,2):
  print(i)

n1=123
a=10
print(n1%10)
print(n1%100//10)
print(n1%1000//100)
print(n1%10000//1000)
print(n1%100000//10000)
print(n1%1000000//100000)
# print (5)
# print(4)
# print(3)

n1=12345
a=10
print(n1%a)
print(n1% (a*10)//a)
a=a*10
print(n1%(a*10)//a)
print(n1%10000//1000)
print(n1%100000//10000)
print(n1%1000000//100000)

n1=12345
a=10
print(n1%a)
print(n1% (a*10)//a)
a=a*10
print(n1%(a*10)//a)
a=a*10
print(n1%(a*10)//a)
a=a*10
print(n1%(a*10)//a)
a=a*10
print(n1%(a*10)//a)

n1=12345678
a=10
print(n1%a)
print(n1% (a*10)//a)
cnt=1
while(cnt <7 ):
  a=a*10
  print(n1%(a*10)//a )
  cnt=cnt+1



"""### Numpy"""

import numpy as np

n1 = np.array([1,2,3,4,5])

print(n1)

n1+5

# create array of randam integer
n2 = np.random.randint(1,100,10)
print(n2)

n3 = np.zeros(10)
print(n3)

for i in range(10) :
  n3[i] = n2[i] + 5

print(n3 , n2)

# create function to accept array and add 5 to each element
def myadd(n2) :
  n3 = np.zeros(len(n2) )
  for i in range(len(n2)) :
    n3[i] = n2[i] + 5
  return n3

# Commented out IPython magic to ensure Python compatibility.
n4 = np.random.randint(1,100,1000000)
# print(n4)
# %timeit n22 = myadd(n4)
# print(n22)

# Commented out IPython magic to ensure Python compatibility.
# %timeit n23 = n4 + 5



"""### Pandas"""

import pandas as pd

url = "https://raw.githubusercontent.com/sarwansingh/Python/refs/heads/master/ClassExamples/data/iris.csv"
df1 = pd.read_csv(url)

df1.head()

df1.describe()



"""### Machine learning

"""

#step 1  : load data
url = "https://raw.githubusercontent.com/sarwansingh/Python/refs/heads/master/ClassExamples/data/iris.csv"
df1 = pd.read_csv(url)

# # step 2 : divide the data vertically
# keep first four columns in x
# keep last column in y

X = df1.iloc[: , 0:4]  # [rows , cols ] [ all rows : , first 4 columns 0:4]
Y = df1.iloc[:,4]

print(X.shape, Y.shape)

# apply machine learning algorithm
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

# step 4 : fit data in the model
model.fit(X,Y)

#step 5 : predict data
model.predict([[5.1,3.5,1.4,0.2]])

model.predict([[5.0,2.0,3.5,1.0]])

model.predict ( [[4.0, 3.2, 4.2, 5]])



"""### Summary

"""

#step 1  : load data
import pandas as pd
url = "https://raw.githubusercontent.com/sarwansingh/Python/refs/heads/master/ClassExamples/data/iris.csv"
df1 = pd.read_csv(url)

df1.shape

# # step 2 : divide the data vertically
# keep first four columns in x   = nxm
# keep last column in y   = nx1

X = df1.iloc[: , 0:4]  # [rows , cols ] [ all rows : , first 4 columns 0:4]
Y = df1.iloc[:,4]

print (X.shape, Y.shape)

# Step  3: apply machine learning algorithm
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model

#step 4 : train the model with data
model.fit(X,Y)

#step 5 : predicting the result
res= model.predict([[5.1,3.5,1.4,0.2]])

res

sw = float( input ("enter sepal width"))
sl = float( input ("enter sepal length"))
pl = float( input ("enter petal length"))
pw = float( input ("enter petal width"))
res= model.predict([[sw, sl, pl, pw]])
print(" flower type is  " , res[0])



"""### Result prediction"""

# Step 1 : load data
url ="https://raw.githubusercontent.com/sarwansingh/Python/refs/heads/master/ClassExamples/data/student-pass-fail-data.csv"
df = pd.read_csv(url)
df.shape

#step 2 : divide
X = df.iloc[: , :2]
Y = df.iloc[:,2]
print(X.shape, Y.shape)

# Step 3 : use machine learning algo
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model

# step 4 : fit the data
model.fit(X,Y)

# step 5 : predict result
import numpy as np
res = model.predict([[5,26]])
print( np.round(res[0]*100,2))

res = model.predict([[3,36]])
print( np.round(res[0]*100,2))

res = model.predict([[5,24]])
print( np.round(res[0]*100,2))